### ISSUE TITLE
Delay on long button press at first boot

### ISSUE THREAD

**Issue by thatblend** [rebane2001/chanduino#5]
I love that there's been 2 version releases in a day, I really like the board location retention and thread watcher. There's an issue though (it was in the initial version too) when I first boot the device where the long press of a button seems to have a noticeable delay (about 3 seconds) before the actual "loading" popup appears. This doesn't happen when I'm on a board and go into a thread and it doesn't happen the second time I go into the boards main menu to select a board.

https://streamable.com/yzm0rm

**Comment by rebane2001** [comment]
The ESP32 is really slow (compared to modern x86 computers) and 4chan forces me to use TLS (https), so I have to run some complicated cryptography code to connect to the webserver (TLS handshake). However, I can tell the webserver to keep my connection open, so that I do not need to go through the handshake process for every request I make. This means that after a connection is made, I can send new requests really fast. But the first request/handshake is always going to be very slow (several seconds).

You might think that it is possible to perform the handshake during the initial load of the board list, but this is unfortunately not possible due to the way I am using ArduinoJSON (which doesn't support HTTP/1.1, the version of HTTP that is required to keep a connection open).

**Comment by thatblend** [comment]
Oh I see, I thought the handshake was performed upon boot so it seemed strange that there was the button delay, but that makes sense.
